### PR TITLE
Added mobile support to jsnes

### PR DESCRIPTION
**Pull request by joeheyming**
Using hammer.js I added a tap/hold/release function that has been tested on an ipad.
I provided mock up html and js files that work on a dummy apache server.

### CODE REVIEW

**Comment by drakmail** [comment]
I'm used [nipple.js](https://github.com/yoannmoinet/nipplejs) in my private fork and it working awesome on iPad. It can solve problem with virtual joypad.

**Comment by bfirsh** [comment]
Thanks @joeheyming! It'd be great to get this supported properly, rather than it just be an experiment.

I think at the very least, we should have some built in code that does browser detection, and if it is a mobile browser, attempts to add overlay controls. That can be in the main emulator -- I don't think it needs to be separate.

@drakmail is the code in your fork good enough for a pull request?

**Comment by drakmail** [comment]
@bfirsh unfortunately the fork is full of dirty hacks 😅  Also I'm not sure that I could remember where was the fork hosted =/

**Comment by joeheyming** [comment]
Hey!  My hacks are clean :-)!  

But seriously, I wrote this so long ago, I probably would just rewrite it if I had time.

**Comment by bfirsh** [comment]
The web stuff for the emulator is now in a separate repository, so I've moved this to here. :) https://github.com/bfirsh/jsnes-web/issues/20

**Pull request closed without merging**
