### PR TITLE
HTML5 WebAudio API

### LINKED ISSUE #7: Add Webkit Web Audio Support
I see you've already added moz audio and a flash fallback for audio support.
There's an api for macintosh chrome and experimental builds of safari that is similar to moz audio.
I thought you should know about http://chromium.googlecode.com/svn/trunk/samples/audio/index.html
To enable web audio support in chrome you have to enable it in about:flags

### PR DESCRIPTION
**Pull request by webdevbyjoss**
In this branch:
- HTML5 WebAudio API used by default for sound output
- Fallback to Flash via DynamicAudio.JS remains for IE8-11

Because WebAudio API AudioBuffer works with Float32Array, we need to convert the JSNES output from Int array to Float32Array. 

It is possible to improve the performance by updating the papu.js -> sample() method to produce Float32Array or even directly AudioBuffer (with backward compatible conversion to Int16Array for DynamicAudio.JS/Flash)

Resolves #7 and #15 

@bfirsh please take a look

### CODE REVIEW

**Comment by workhorsy** [comment]
Nice! I just tested this on Chrome and Firefox. It works, and removes the 3 second delay in the sound. Confirmed to work.

**Comment by bfirsh** [comment]
Nice! Will try this out this weekend - thanks. :)

**Comment by webdevbyjoss** [comment]
Before merging this PR, I would address the TODO: and create the audio buffer right in papu.js, 
with appropriate conversion to flash-fallback.

**Comment by Venediktoff** [comment]
Tested on Chrome and Firefox - works well. At one point the framerate fropped to 3 fps, but I can't state it is related to this improvement. 
Good job, @webdevbyjoss !

**Comment by wyatt8740** [comment]
This should really be mono - the NES is not a stereo console. Is there at least a way to switch it back to mono? I am aware the 2A03 has two channels internally, but they are never exposed on ANY NES or famicom console or arcade machine. They are always mixed down.

**Comment by webdevbyjoss** [comment]
@wyatt8740 it actually mono, my bad for naming this thing inproperly
it just outputs the same staff into R & L channels

**Comment by wyatt8740** [comment]
@webdevbyjoss Ah, okay. Probably should have actually looked at the code :\

**Comment by bfirsh** [comment]
I wonder if this would make sense to put in dynamicaudio. Then we would get a reusable API which let you write audio with flash fallback.

Are there any limitations of the dynamicaudio API that means it can't live there?

**Comment by webdevbyjoss** [comment]
@bfirsh  that is brilliant idea, let me prepare the appropriate PR there

**Comment by webdevbyjoss** [comment]
@bfirsh here you are https://github.com/bfirsh/dynamicaudio.js/pull/7
let me know what do you think

**Pull request closed without merging**
