### PR TITLE
Add save/load state examples to README file

### PR DESCRIPTION
**Pull request by ninjadynamics**
Hello again,

This is a rather simple pull request, just added load/save state examples to the readme file.

### CODE REVIEW

**Comment by bfirsh** [comment]
Super, thanks @ninjadynamics! Looks like your git repository is in a tangle though -- you have a merge commit and some commits from master in there, and there are merge conflicts.

It might be easiest to start a new branch based off `bfirsh:master`, then cherry pick the commits you want to keep.

Also: would you mind putting the saving state example at the end of that little block of examples? I think have running frames and controls first makes more sense as a narrative of how it works.

**Comment by ninjadynamics** [comment]
Hi! Sure, I'll try to do some housekeeping! This is actually my first time collaborating on github, so sorry about that! '^__^

**Comment by ninjadynamics** [comment]
Alright, I think I have everything in order now. :)

My repository contains only 3 little changes:
- Replaced "let" with "var" to fit the project code style (also the linter was complaining)
- Added the save/load state examples to the readme file (at the end of the block, as requested)
- Added 'workflow_dispatch' to the workflow file, so that JSNES can be built on demand on the GitHub 'Actions' tab

**Comment by bfirsh** [comment]
Wonderful, thanks. Unfortunately it still looks like your branch is broken. You might want to google how to rebase a git branch, or create a new branch and cherry pick.

**Comment by ninjadynamics** [comment]
Unfortunately, I can't see any conflicts on my side... Should I "refork" JSNES, apply the changes and create a new pull req?

**Comment by bfirsh** [comment]
You don't need to refork -- probably best to make a new branch, then cherry pick the commits you need. GitHub docs should be able to help you out here, and I can also do myself when I have a bit more time :)

**Comment by ninjadynamics** [comment]
I tried rebasing as you suggested. All tests green and GitHub reports no merge conflicts. If it doesn’t work, I don’t know what else to do. 😐

**Pull request closed without merging**
